### ISSUE TITLE
[BUG] Client Crash when running multiple clients.

### ISSUE THREAD

**Issue by Mivoc** [markdwags/Razor#155]
ClassicUO Client, Windows 10, Intel i7, Nvidia GTX 3080

- Game crashes while playing.
- Steps to reproduce
- Run multiple game clients. This crash usually occurs when another client is macroing while playing on another account.
  
**Error from Application Event Viewer in Windows.**
Faulting application name: ClassicUO.exe, version: 0.1.7.0, time stamp: 0xf038433a
Faulting module name: KERNELBASE.dll, version: 10.0.19041.662, time stamp: 0xec58f015
Exception code: 0xe0434352
Fault offset: 0x000000000002d759
Faulting process id: 0x2958
Faulting application start time: 0x01d702838590f970
Faulting application path: C:\UORenaissance\ClassicUO\ClassicUO.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 5d8cce53-9f41-42de-9a55-d0e1934a0f68
Faulting package full name: 
Faulting package-relative application ID:

**Comment by markdwags** [comment]
What leads you to believe it's related to Razor?  Have any logs indicating as much?  Any crash logs in the CUO folder? Any logs int the Razor folder?

**Comment by Mivoc** [comment]
hmm, not sure actually. Just trying to find help with this issue thats affect myself and my friends. It may not be related to Razor.
I found the crash logs in the UO:C folder. Here is the most recent one.
######################## [START LOG] ########################
ClassicUO [STANDARD_BUILD] - 0.1.7.0 - 02/13/2021 00:27:00
OS: Win32NT x64
Thread: CUO_MAIN_THREAD

Shard: login.uorenaissance.com
ClientVersion: 5.0.8.3

Exception:
System.InvalidOperationException: Texture2D creation failed! Error Code: The GPU will not respond to more commands, most likely because of an invalid command passed by the calling application. (0x887A0006)
   at Microsoft.Xna.Framework.FNALoggerEXT.FNA3DLogError(IntPtr msg) in D:\Progetti\ClassicUO\client\external\FNA\src\FNALoggerEXT.cs:line 95
   at Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_CreateTexture2D(IntPtr device, SurfaceFormat format, Int32 width, Int32 height, Int32 levelCount, Byte isRenderTarget)
   at Microsoft.Xna.Framework.Graphics.Texture2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipMap, SurfaceFormat format) in D:\Progetti\ClassicUO\client\external\FNA\src\Graphics\Texture2D.cs:line 94
   at ClassicUO.IO.Resources.AnimationsLoader.ReadMULAnimationFrame(AnimationDirection& animDir, UOFile reader) in D:\Progetti\ClassicUO\client\src\IO\Resources\AnimationsLoader.cs:line 3382
   at ClassicUO.IO.Resources.AnimationsLoader.LoadAnimationFrames(UInt16 animID, Byte animGroup, Byte direction, AnimationDirection& animDir) in D:\Progetti\ClassicUO\client\src\IO\Resources\AnimationsLoader.cs:line 3120
   at ClassicUO.Game.GameObjects.Mobile.DrawInternal(UltimaBatcher2D batcher, Mobile owner, Item entity, Int32 x, Int32 y, Boolean mirror, SByte frameIndex, Boolean hasShadow, UInt16 id, Byte animGroup, Byte dir, Boolean isHuman, Boolean isParent, Boolean isMount, Boolean forceUOP, Single alpha) in D:\Progetti\ClassicUO\client\src\Game\GameObjects\Views\MobileView.cs:line 546
   at ClassicUO.Game.GameObjects.Mobile.Draw(UltimaBatcher2D batcher, Int32 posX, Int32 posY) in D:\Progetti\ClassicUO\client\src\Game\GameObjects\Views\MobileView.cs:line 439
   at ClassicUO.Game.Scenes.GameScene.DrawWorld(UltimaBatcher2D batcher, Matrix& matrix, Boolean use_render_target) in D:\Progetti\ClassicUO\client\src\Game\Scenes\GameScene.cs:line 1039
   at ClassicUO.Game.Scenes.GameScene.Draw(UltimaBatcher2D batcher) in D:\Progetti\ClassicUO\client\src\Game\Scenes\GameScene.cs:line 872
   at ClassicUO.GameController.Draw(GameTime gameTime) in D:\Progetti\ClassicUO\client\src\GameController.cs:line 454
   at Microsoft.Xna.Framework.Game.Tick() in D:\Progetti\ClassicUO\client\external\FNA\src\Game.cs:line 548
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\Progetti\ClassicUO\client\external\FNA\src\Game.cs:line 855
   at Microsoft.Xna.Framework.Game.Run() in D:\Progetti\ClassicUO\client\external\FNA\src\Game.cs:line 416
   at ClassicUO.Client.Run() in D:\Progetti\ClassicUO\client\src\Client.cs:line 73
   at ClassicUO.Bootstrap.Main(String[] args) in D:\Progetti\ClassicUO\client\src\Main.cs:line 240
######################## [END LOG] ########################

**Comment by markdwags** [comment]
I can confirm for a fact that many people run ClassicUO and Razor, multiple clients, on that shard and others with no issues. Based on the error, it looks like it's related to ClassicUO so I'd recommend posting your issue there.

https://github.com/andreakarasho/ClassicUO/issues

It's looking like something related to the ClassicUO framework and your GPU.  Good luck!
