### ISSUE TITLE
There was an exception while attempting to load 'C:\Games\Electronic Arts\Ultima Online Classic\cliloc.ENU':

### ISSUE THREAD

**Issue by BrokeUOplayer** [markdwags/razor#233]
Using OSI with classic client just trying to start RAZOR (without UO Launcher).  

This just occurred when UO performed their latest patch on 7/28  

UO launcher no longer works period!

Windows 10 running X86  

RAZOR version 1.0.14

There was an exception while attempting to load 'C:\Games\Electronic Arts\Ultima Online Classic\cliloc.ENU':
System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: count
   at System.IO.BinaryReader.Read(Byte[] buffer, Int32 index, Int32 count)
   at Ultima.StringList..ctor(String language)
   at Assistant.Language.LoadCliLoc()

**Comment by dcamilleri1981** [comment]
I have the same issue, happened after latest Client update

**Comment by BrokeUOplayer** [comment]
Well I have come to the conclusion, that this site is about dead, I'm guessing that RAZOR is no longer supported. Such a shame, it was an awesome program!

**Comment by ReyD2** [comment]
I've got this same issue ☹

**Comment by Macil2018** [comment]
Having the same issue. I've even tried going into Razor's configuration file to manually change the location of where my installation folder is (which is always some location on my D drive which is nowhere close to where my install folder is). And even after I change it, I get the same error, only to go back and look at the configuration to see that Razor has once more changed my install folder back to the wrong folder. It absolutely won't stop using D:\Games\UO\ as it's install folder.

And to go one step further, I even tried copying ALL my UO files to that D:\Games\UO\ location, even going as far as to make those corresponding folders for the heck of it. And it STILL doesn't work.

**Comment by markdwags** [comment]
This has been fixed in the latest development build.

**Comment by ghost** [comment]
Unfortunately, I'm having the same problem as him - even with the newest dev build. It didn't happen for some time, I thought it was definitely fixed for a while, but here it is once again after I played for a couple of hours.
